// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// USANDO CHAVES ABSOLUTAS DO PROJETO YAGISISJKODCDHCZMPBF (FIXED)
// Isso resolve o erro 401 Unauthorized de forma definitiva
const SUPABASE_URL = "https://yagisisjkodcdhczmpbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhZ2lzaXNqa29kY2RoY3ptcGJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NzI2NDMsImV4cCI6MjA3NzI0ODY0M30._oElqEESZxNdwAkSqyew3AfouIZlEbwkbd8QCcHal8g";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});